config/routes.rb
Rails.application.routes.draw do
  resources :events, :only => ['create','destroy'] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
		events = Event.where("(event_type = ? and parent_id != ?) or (event_type = ? and parent_id = ?)",'recurring',0,'single',0)
		@events = Array.new
		events.each do |event|
			ev = Hash.new
			ev['id'] = event.id
			ev['title'] = event.title
			ev['extendedProps'] = { 'type' => event.event_type,'start_time' => event.start_time,'end_time' => event.end_time}
			ev['allDay'] = true
			ev['start'] = event.start_date
			ev['end'] = event.end_date
			if event.event_type == 'recurring'
				if event.reccurring_days != ""
					ev['extendedProps']['reccurring_days'] = JSON.parse(event.reccurring_days)
				else
					ev['extendedProps']['reccurring_days'] = ["0"]
				end
			end
			@events.push(ev)
		end
		# raise @events.inspect
		@event = Event.new
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # POST /events.json

  before_action :set_event, only: ['destroy']
  def create

    w_days = params[:event][:reccurring_days]
    params['event']['reccurring_days'] = params['event']['reccurring_days'].to_s
  
    if params['event']['event_id'].blank?
      start_date = Date.parse(params[:event][:start_date])
      
      @event = Event.new(event_params)
      @event.parent_id = 0
      
      if params[:event][:event_type] == 'single'
        end_date =start_date
        @event.end_date = start_date
      else
        end_date = Date.parse(params[:event][:end_date]) 
      end

      respond_to do |format|
        if @event.save
          d = start_date
          if @event.start_date != @event.end_date
            while d <= end_date
              if w_days.include? d.wday.to_s
                event = Event.new(event_params) 
                event.start_date =  d.strftime("%Y-%m-%d")
                event.end_date = d.strftime("%Y-%m-%d")
                event.parent_id = @event.id
                event.save
              end
              d += 1
            end  
          end
          format.html { redirect_to root_url, notice: 'Event was successfully added.' }
        else
          format.html { redirect_to root_url, notice: 'Event was not added.' }
        end
      end
    else
      @child = Event.find(params[:event][:event_id])
      @parent = Event.find(@child.id)
      if @child.event_type === 'single'
        if @child.update(event_params)
          redirect_to root_url, notice: 'This Event was successfully updated.' 
        else
          redirect_to root_url, notice: 'This Event was not updated.' 
        end
      else
        start_date = Date.parse(@parent.start_date.to_s)
        if params[:edit_as] === 'single'
          @child = Event.find(params[:event][:event_id])
          @child.start_time = params[:event][:start_time]
          @child.end_time = params[:event][:end_time]
          @child.title = params[:event][:title]
          if @child.save
            redirect_to root_url, notice: 'This Event was successfully updated.' 
          end
        else
          @child = Event.find(params[:event][:event_id])
          @parent = Event.find(@child.parent_id)
          w_days_existing = @parent.reccurring_days
          child_events = Event.where(:parent_id => @parent.id).where("start_date >= ?",@child.start_date).all
          
          # removing the weekdays events if present
          diff = JSON.parse(w_days_existing) - w_days
          unless diff.blank?
            child_events.each do |ev|
              start_date = ev.start_date
              if diff.include? start_date.wday.to_s
                ev.destroy
              end
            end
          end

          # child_events.update(event_params)
          # adding new weekdays events if present
          new_wdays = w_days - JSON.parse(w_days_existing)
          exist_wdays = w_days & JSON.parse(w_days_existing)
          d = @child.start_date
          end_date = Date.parse(@parent.end_date.to_s)

          unless new_wdays.blank?
            while d <= end_date
              if new_wdays.include? d.wday.to_s
                event = Event.new(event_params) 
                event.start_date =  d.strftime("%Y-%m-%d")
                event.end_date = d.strftime("%Y-%m-%d")
                event.parent_id = @parent.id
                event.save
              end
              d += 1
            end 
          end

          Event.where(:parent_id => @parent.id).where("start_date >= ?",@child.start_date).all.each { |e| e.update(event_params)}


          # events = Event.where("parent_id = ?  and start_date >= ?",@parent.id,@child.start_date)
          # events.update(event_params)

          redirect_to root_url, notice: 'This Event was successfully updated.'
          end
        end
      end  
    end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Event was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :event_type, :start_date, :end_date, :reccurring_days,:start_time,:end_time,:parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/application/index.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <%= notice %>
</div>
<% end %>
<div id='calendar'></div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Event</h4>
      </div>
      <%= simple_form_for @event do |f| %>
      <div class="modal-body">
        <input type="hidden" value="" id="event_id" name="event[event_id]">
        
        <!-- if the event is a recurring then edit as single or multiple -->
        
        <div class="form-group" id="recurring_event" style="display:none">
          <p>This is a recurring Event. Edit this as </p>

          <div class="row">
            <div class="col-md-12">
              <label for=""></label>
            </div>
            <div class="col-md-12">
              <div class="col-md-6"> <input type="radio" checked class="edit_as" name="edit_as" value="single">This
                Event only </div>
              <div class="col-md-6">
                <input type="radio" name="edit_as" class="edit_as" value="multiple">All further Events
              </div>
            </div>
          </div>
        </div>
        
        <!-- title -->
        <div class="form-group">
          <div class="row">
            <div class="col-md-2">
              <label for="">Title</label>
            </div>
            <div class="col-md-10">
              <input type="text" id="title" class="form-control input-sm" name="event[title]" required placeholder="Enter Title">
            </div>
          </div>
        </div>

        <!-- start date and end date -->
        <div class="form-group">
          <div class="row">
            <div class="col-md-2">
              <label for="">Start Date</label>
            </div>
            <div class="col-md-4">
              <input type="text" id="datepicker1" name="event[start_date]" class="form-control datepicker input-sm">
            </div>
            <div id="datepicker2_div" style="display:none">
              <div class="col-md-2">
                <label for="">End Date</label>
              </div>
              <div class="col-md-4">
                <input type="text" id="datepicker2" name="event[end_date]" class="form-control datepicker input-sm">
              </div>
            </div>
          </div>
        </div>

        <!-- start time and end time -->
        <div class="form-group">
          <div class="row">
            <div class="col-md-2">
              <label for="">Start Time</label>
            </div>
            <div class="col-md-4">
              <input type="text" id="datepicker3" name="event[start_time]" class="form-control datepicker input-sm">
            </div>
            <div class="col-md-2">
              <label for="">End Time</label>
            </div>
            <div class="col-md-4">
              <input type="text" id="datepicker4" name="event[end_time]" class="form-control datepicker input-sm">
            </div>
          </div>
        </div>

        <!-- event type -->
        <div class="form-group">
          <div class="row">
            <div class="col-md-2">
              <label for="">Type</label>
            </div>
            <div class="col-md-10">
              <select name="event[event_type]" id="event_type" required class="form-control input-sm">
                <option value="">Select Type</option>
                <option value="single">Single</option>
                <option value="recurring">Reccurring</option>
              </select>
            </div>
          </div>
        </div>

        <!-- days selection -->
        <div class="form-group" id="recurring_days_div">
          <div class="row">
            <div class="col-md-2">
              <label for="">Recurring</label>
            </div>
            <div class="col-md-10">
              <input type="checkbox" value=0 class="days_checkbox" name="event[reccurring_days][]">Sun&nbsp;
              <input type="checkbox" value=1 class="days_checkbox" name="event[reccurring_days][]">Mon&nbsp;
              <input type="checkbox" value=2 class="days_checkbox" name="event[reccurring_days][]">Tue&nbsp;
              <input type="checkbox" value=3 class="days_checkbox" name="event[reccurring_days][]">Wed&nbsp;
              <input type="checkbox" value=4 class="days_checkbox" name="event[reccurring_days][]">Thu&nbsp;
              <input type="checkbox" value=5 class="days_checkbox" name="event[reccurring_days][]">Fri&nbsp;
              <input type="checkbox" value=6 class="days_checkbox" name="event[reccurring_days][]">Sat&nbsp;
            </div>
          </div>
          <div class="row">
            <div class="col-md-8 offset-md-3">
              <label id="reccurring_days-error" class="error" for="event[reccurring_days][]"></label>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', event_path(0), method: :delete, id: "delete_event", data: { confirm: 'Are you sure to remove this event ?' },class: "btn btn-sm btn-danger" %>
        <input type="submit" class="btn btn-primary btn-sm" id="submit_btn" name="submit">
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $(".edit_as").change(function(){
      if($(this).val() === 'single'){
        $("#datepicker1").attr('disabled',true)
        $("#datepicker2").attr('disabled',true)
        $("#recurring_days_div").hide()
      }else{
        $("#recurring_days_div").show()
      }
    })

  })
</script>

<!-- Validate the event form -->
<script>
var event_type = 'single'
$("#new_event").validate({
  rules: {
    'event[title]': {
      required: true,
    },
    'event[event_type]': "required",
    'event[start_date]': "required",
    'event[reccurring_days][]': "required"
  },
  messages: {
    'event[title]': "Please enter Title",
    'event[event_type]': "Please select event type",
    'event[start_date]': "Please enter event start date",
    'event[reccurring_days][]': "Please select at least one day",
    'event[end_date]': "Please enter end date",
  }
});
</script>
<!-- end of validation -->
<!-- setting date -->
<script>
function setDate(date) {
  let fulldate = new Date(date)
  let dd = String(fulldate.getDate()).padStart(2, '0');
  let mm = String(fulldate.getMonth() + 1).padStart(2, '0'); //January is 0!
  let yyyy = fulldate.getFullYear();
  return yyyy + '-' + mm + '-' + dd;
}
</script>
<!-- end -->
<!-- show event form -->
<script>
function showModal(eventObj = '', info = '') {
  $('#myModal').modal({
    show: true
  });
  if (eventObj != '') {
    if($(".edit_as").val() === 'single' ){
      $("#recurring_days_div").hide()
    }
    $("#delete_event").show();
    $("#delete_event").attr("href", "/events/" + eventObj.id)
    $("#datepicker3").val(eventObj.extendedProps.start_time);
    $("#datepicker4").val(eventObj.extendedProps.end_time);
    // checking if reccurring event setting the days checkboxes
    if (eventObj.extendedProps.type == 'recurring') {
      let days_array = eventObj.extendedProps.reccurring_days
      for (var i = 0; i < days_array.length; i++)
        $(':checkbox[value="' + days_array[i] + '"]').prop('checked', true);
      var start_date = setDate(eventObj.start)
    } else {
      var start_date = setDate(eventObj.start)
    }
    // end

    // setting event modal fields--------------->
    $(".modal-body #datepicker1").val(start_date);
    $(".modal-body #event_id").val(eventObj.id);
    $(".modal-body #event_type").val(eventObj.extendedProps.type)
    $(".modal-body #title").val(eventObj.title);
    $("#submit_btn").val("Update");
    $("#datepicker1").attr('disabled',true)
  } else {
    $(':checkbox').prop('checked', false);
    $("#datepicker1").attr('disabled',false)
    $("#datepicker2").attr('disabled',false)
    $(".modal-body #datepicker2_div").hide();
    $(".modal-body #datepicker1").val(info.dateStr);
    $(".modal-body #datepicker2").val('');
    $(".modal-body #event_type").val('')
    $(".modal-body #title").val('');
    $("#delete_event").hide()
    $("#recurring_days_div").hide()
    $("#submit_btn").val("Add");
  }
}
// end


// remove juery validation after close
$('#myModal').on('hidden.bs.modal', function() {
  var $alertas = $('#new_event');
  $("#event_id").val("");
  $("#recurring_days_div").hide()
  $("#recurring_event").hide();
  $alertas.validate().resetForm();
  $alertas.find('.error').removeClass('error');
  $('#reccurring_days-error').addClass('error');
});
// end

// calendar UI code------------------->
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');
  var calendar = new FullCalendar.Calendar(calendarEl, {
    events: <%=  @events.to_json.html_safe %>,
    plugins: ['dayGrid', 'interaction'],
    eventClick: function(info) {
      var eventObj = info.event;
      if (eventObj.extendedProps.type == 'recurring') {
        let answer = confirm("You are editing a reccurring event. Are you sure to continue ?");
        if (answer)
          showModal(eventObj, '');
        $("#recurring_event").show();
      } else {
        $("#recurring_event").hide();
        showModal(eventObj, '');
      }
    },
    dateClick: function(info) {
      showModal('', info);
    }
  });

  calendar.render();
});
// end-------------->
</script>
<!-- on change of event type -->
<script>
$("#event_type").on('change', function() {
  event_type = $(this).val();
  if ($(this).val() === 'recurring') {
    $("#datepicker2_div").show()
    $("#datepicker2").rules('add', 'required');
    $("#recurring_days_div").show();
  } else {
    $("#datepicker2_div").hide()
    $("#recurring_days_div").hide();
    $("#datepicker2").rules('remove', 'required');
    $(".modal-body #datepicker2").val('');
    $(':checkbox').prop('checked', false);
  }
})
</script>

<script type="text/javascript">
$(document).ready(function() {
  $('#myModal').on('shown.bs.modal', function() {
    // date pickers
    $('#datepicker1').datetimepicker({
      format: 'YYYY-MM-DD'
    });
    $('#datepicker2').datetimepicker({
      useCurrent: false,
      format: 'YYYY-MM-DD' //Important! See issue #1075
    });

    $("#datepicker1").on("dp.change", function(e) {
      $('#datepicker2').data("DateTimePicker").minDate(e.date);
    });
    $("#datepicker2").on("dp.change", function(e) {
      $('#datepicker1').data("DateTimePicker").maxDate(e.date);
    });

    // time pickers
    $('#datepicker3').datetimepicker({
      format: 'LT'
    });
    $('#datepicker4').datetimepicker({
      useCurrent: false,
      format: 'LT' //Important! See issue #1075
    });
  })
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calander</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



    <!-- JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.14.0/additional-methods.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    
    <!-- CSS Stylesheets -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href='https://unpkg.com/@fullcalendar/core@4.3.1/main.min.css' rel='stylesheet' />
    <link href='https://unpkg.com/@fullcalendar/daygrid@4.3.0/main.min.css' rel='stylesheet' />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel='stylesheet' />
   
    <!-- full calendar JS -->
    <script src='https://unpkg.com/@fullcalendar/core@4.3.1/main.min.js'></script>
    <script src="https://unpkg.com/@fullcalendar/interaction@4.3.0/main.min.js"></script>
    <script src='https://unpkg.com/@fullcalendar/daygrid@4.3.0/main.min.js'></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>